Hw01
DanilFlint/2024-05-otus-spring-Didenko pull request #1
Opened 2024-07-18 19:30 UTC by DanilFlint

2024-07-21 19:59 UTC, VladimirMagerov requested changes

2024-07-21 19:59 UTC, VladimirMagerov commented on hw01/src/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
`pom.xml` надо достать из `src` положить в `hw01` директорию, иначе нарушаем стандартную структуру maven проекта.

2024-07-21 19:59 UTC, VladimirMagerov commented on hw01/src/main/java/ru/otus/hw/service/TestCommandProcessorImpl.java
> +        var userAnswer = processUserAnswer(ioService);
В этом домашнем задании не нужно было реализовывать считывание ответа - только чтение вопросов из файла и их вывод в консоль с вариантами ответов, поэтому давайте сейчас мы обработку ответа отсюда уберём, и вы используете её уже во втором ДЗ, где это уже надо будет реализовать.

2024-07-22 19:26 UTC, DanilFlint commented on hw01/src/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
++

2024-07-22 19:26 UTC, DanilFlint commented on hw01/src/main/java/ru/otus/hw/service/TestCommandProcessorImpl.java
> +        var userAnswer = processUserAnswer(ioService);
++

2024-07-24 20:19 UTC, VladimirMagerov approved these changes

2024-07-24 20:19 UTC, VladimirMagerov commented on hw01/src/main/java/ru/otus/hw/dao/CsvQuestionDao.java
> +                    .withSeparator(';').withType(QuestionDto.class).withSkipLines(1).build();
При первом ревью не обратил внимания - такие вызовы по цепочке лучше оформлять отдельно в каждой строке, так намного лучше читается код:
![image](https://github.com/user-attachments/assets/e06c2cdd-d6f3-49c7-82ee-756c81ae0205)

2024-07-25 06:14 UTC, merged