Hw02
DanilFlint/2024-05-otus-spring-Didenko pull request #2
Opened 2024-08-01 19:33 UTC by DanilFlint

2024-08-05 20:03 UTC, VladimirMagerov requested changes

2024-08-05 20:03 UTC, VladimirMagerov commented on hw02/src/test/java/CsvQuestionDAOTest.java
> +        TestFileNameProvider fileNameProvider = mock(TestFileNameProvider.class);
Предлагаю уйти от ручного создания моков и использовать декларативный подход через аннотации `@Mock` и `@InjectMocks`

2024-08-05 20:03 UTC, VladimirMagerov commented on hw02/src/main/java/ru/otus/hw/utils/Utils.java
> +public class Utils {
Просто `Utils` звучит максимально обобщённо, предлагаю уточнить - например, `AnswerUtils` или в таком духе.

2024-08-05 20:03 UTC, VladimirMagerov commented on hw02/src/test/java/CsvQuestionDAOTest.java
> +import org.junit.jupiter.api.Test;
По заданию нужно добавить ещё и тесты сервисов  с моком зависимостей, предлагаю это сделать.

2024-08-05 20:03 UTC, VladimirMagerov commented on hw02/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +        AnswerService answerService = new AnswerServiceImpl(ioService);
Если мы работаем со Спрингом, `AnswerService ` и `QuestionService` должны быть бинами спринга и соответствующим образом сконфигурированы, как и другие сервисы, а не созданы вручную. Это надо поправить.

2024-08-06 19:25 UTC, DanilFlint commented on hw02/src/main/java/ru/otus/hw/utils/Utils.java
> +public class Utils {
++

2024-08-06 19:25 UTC, DanilFlint commented on hw02/src/test/java/CsvQuestionDAOTest.java
> +import org.junit.jupiter.api.Test;
++

2024-08-06 19:26 UTC, DanilFlint commented on hw02/src/test/java/CsvQuestionDAOTest.java
> +        TestFileNameProvider fileNameProvider = mock(TestFileNameProvider.class);
++

2024-08-06 19:26 UTC, DanilFlint commented on hw02/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +        AnswerService answerService = new AnswerServiceImpl(ioService);
++

2024-08-09 10:36 UTC, VladimirMagerov approved these changes

2024-08-10 04:26 UTC, merged